# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lagotto < Formula
  desc "Sniff out Go layout smells (Receiver Monolith, Decomposition Theatre, Aggregate Holder, and more)."
  homepage "https://github.com/CaliLuke/lagotto"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CaliLuke/lagotto/releases/download/v0.1.2/lagotto_0.1.2_darwin_amd64.tar.gz"
      sha256 "a9c56e3aad5611a1e1b1910817b8d1f5d6c2c47ddcaaa2b1676d8a6c5cb11fd0"

      define_method(:install) do
        bin.install "lagotto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CaliLuke/lagotto/releases/download/v0.1.2/lagotto_0.1.2_darwin_arm64.tar.gz"
      sha256 "f1ef350b1a097bb2e55660ceb3bb317fc1b82cca759c91119de3c82b348f0e0d"

      define_method(:install) do
        bin.install "lagotto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/lagotto/releases/download/v0.1.2/lagotto_0.1.2_linux_amd64.tar.gz"
      sha256 "d217a4e775b3444cae6340f8c3363754834f7b1c2c27e3a5536332873f9cad34"
      define_method(:install) do
        bin.install "lagotto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/lagotto/releases/download/v0.1.2/lagotto_0.1.2_linux_arm64.tar.gz"
      sha256 "5a7709a1d1292f3896d97f457db7fb0681b48d33d5f02913e388a2b79815daef"
      define_method(:install) do
        bin.install "lagotto"
      end
    end
  end

  test do
    system bin/"lagotto", "--version"
  end
end
