# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-argo-mcp" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "34233c24695c66811f640e48161bacaaddec3613106d95f39cf2b48941991b73"
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v#{version}/go-argo-mcp_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ee3f2e1798fd1a3cb387825b7af49bf707b35a7d26e34f98de3de20e81a4e407"
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v#{version}/go-argo-mcp_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "05a6ff15d3f7c996607e6519a1103c8d7e53fd63775779a3a8baebb14aeae1db"
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v#{version}/go-argo-mcp_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4063a33089a1285a695f4fa3f9651187f0ca65c08e63066ac4b247ace88fd164"
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v#{version}/go-argo-mcp_Linux_arm64.tar.gz"
    end
  end

  name "go-argo-mcp"
  desc "Lightweight Go MCP server for Argo Workflows"
  homepage "https://github.com/CaliLuke/go-argo-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-argo-mcp"

  # No zap stanza required

  caveats <<~EOS
    go-argo-mcp exposes Streamable HTTP at http://127.0.0.1:8080/rpc.
    Set ARGO_BASE_URL and optional ARGO_NAMESPACE before starting it.
  EOS
end
