# typed: false
# frozen_string_literal: true

# Generated by the go-argo-mcp release workflow. DO NOT EDIT.
cask "go-argo-mcp" do
  arch arm: "arm64", intel: "x86_64"

  version "0.2.1"
  sha256 arm:   "fdfeb7a59bdc85c8c342cac8bb1ebd37208cd9e46619196989a57f60cc653b56",
         intel: "ccf90d866eebdff00f08501e7feae175892db819de1e21d02dccbd865ff0bf2c"

  url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v#{version}/go-argo-mcp_Darwin_#{arch}.tar.gz"
  name "go-argo-mcp"
  desc "Lightweight Go MCP server for Argo Workflows"
  homepage "https://github.com/CaliLuke/go-argo-mcp"

  binary "go-argo-mcp"
end
