# typed: false
# frozen_string_literal: true

# Generated by the go-argo-mcp release workflow. DO NOT EDIT.
cask "go-argo-mcp" do
  arch arm: "arm64", intel: "x86_64"

  version "0.3.0"
  sha256 arm:   "563ecb8e414ed5bdc936e790b7bcb83be69d47fcbbd6deaac69599213c8c7b35",
         intel: "494b95c6144d150b0714dce8f80070b63283df4de0cb217d6385c6ab1614c91b"

  url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v#{version}/go-argo-mcp_Darwin_#{arch}.tar.gz"
  name "go-argo-mcp"
  desc "Lightweight Go MCP server for Argo Workflows"
  homepage "https://github.com/CaliLuke/go-argo-mcp"

  binary "go-argo-mcp"
end
