# typed: strict
# frozen_string_literal: true

# This file is generated by Earwig's release workflow. DO NOT EDIT.
class Earwig < Formula
  desc "Capture Codex and Claude Code turns for local evaluation"
  homepage "https://github.com/CaliLuke/earwig"
  version "0.1.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.13/earwig_0.1.13_darwin_amd64.tar.gz"
      sha256 "b330beca7765d8bde3717828b699fa08e2bce99ceea0e01f6abfe4df8f95d56c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.13/earwig_0.1.13_darwin_arm64.tar.gz"
      sha256 "f81a59de8ac4a5fc1e2ec237a3a44fc06e64a44180d7e5778a36050dffedd382"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.13/earwig_0.1.13_linux_amd64.tar.gz"
      sha256 "c0c6d6c6deadc6e61ff04f4b28eeecc260b385165117a29d5f8353c9885a9519"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.13/earwig_0.1.13_linux_arm64.tar.gz"
      sha256 "35e86d6686f263be3a5d61501fd40bc6fd078e60a7bc89da006a1c539abbe1be"
    end
  end

  def install
    bin.install "earwig"
    libexec.install "claude-reader"
  end

  service do
    run [opt_bin/"earwig", "watch"]
    environment_variables PATH: std_service_path_env
    keep_alive true
    working_dir var
    log_path var/"log/earwig.log"
    error_log_path var/"log/earwig.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/earwig version")
  end
end
