# typed: strict
# frozen_string_literal: true

# This file is generated by Earwig's release workflow. DO NOT EDIT.
class Earwig < Formula
  desc "Capture Codex and Claude Code turns for local evaluation"
  homepage "https://github.com/CaliLuke/earwig"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.0/earwig_0.1.0_darwin_amd64.tar.gz"
      sha256 "c33741159291a14c542320a893bb88e6e11e0cca7047fc6f353d823934b5a6d0"
    end
    if Hardware::CPU.arm?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.0/earwig_0.1.0_darwin_arm64.tar.gz"
      sha256 "bd335dee4ffc90f6b1e4d734f1d0aa2d0341dfc2cc1346898bff97b68ffc278e"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.0/earwig_0.1.0_linux_amd64.tar.gz"
      sha256 "04db4edc8cd3552b823e08c9f1251b52f2cd7e0aae0055e91c74777e2bea0e22"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.0/earwig_0.1.0_linux_arm64.tar.gz"
      sha256 "b1ed79f3e8823df7ca4d373c3fb35115501cb16e1bafb22caec88277abed4d54"
    end
  end

  def install
    bin.install "earwig"
    libexec.install "claude-reader"
  end

  service do
    run [opt_bin/"earwig", "watch"]
    keep_alive true
    working_dir var
    log_path var/"log/earwig.log"
    error_log_path var/"log/earwig.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/earwig version")
  end
end
