# typed: strict
# frozen_string_literal: true

# This file is generated by Earwig's release workflow. DO NOT EDIT.
class Earwig < Formula
  desc "Capture Codex and Claude Code turns for local evaluation"
  homepage "https://github.com/CaliLuke/earwig"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.1/earwig_0.1.1_darwin_amd64.tar.gz"
      sha256 "566925ac87b6ca9a0e560a38c0999511b8236fa59a9869c8c1ef066c8debae89"
    end
    if Hardware::CPU.arm?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.1/earwig_0.1.1_darwin_arm64.tar.gz"
      sha256 "38393b27058ebee99d609a07b31b1197d7c2146f94f417238b171510ebc23662"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.1/earwig_0.1.1_linux_amd64.tar.gz"
      sha256 "b8ca583025667419a145d666665dd1e2c07759c18ff4eac4a65668c1564bbf4c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/earwig/releases/download/v0.1.1/earwig_0.1.1_linux_arm64.tar.gz"
      sha256 "955dc4cf9f48fe26ddc5720a1ec2da4a2cdf6105474a8fa25feb65dd98072c36"
    end
  end

  def install
    bin.install "earwig"
    libexec.install "claude-reader"
  end

  service do
    run [opt_bin/"earwig", "watch"]
    keep_alive true
    working_dir var
    log_path var/"log/earwig.log"
    error_log_path var/"log/earwig.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/earwig version")
  end
end
