# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoArgoMcp < Formula
  desc "Lightweight Go MCP server for Argo Workflows"
  homepage "https://github.com/CaliLuke/go-argo-mcp"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v0.1.0/go-argo-mcp_Darwin_x86_64.tar.gz"
      sha256 "406f777e95473409106aca7f0f86547abe4ab6df0a5a805e69df4dd5bedcdcc2"

      define_method(:install) do
        bin.install "go-argo-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v0.1.0/go-argo-mcp_Darwin_arm64.tar.gz"
      sha256 "ccdd216edae4f73b7980681c96e959682ed70ce7adcdc8b6b59720f506f60cb7"

      define_method(:install) do
        bin.install "go-argo-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v0.1.0/go-argo-mcp_Linux_x86_64.tar.gz"
      sha256 "2ea3e8ed4d82771105c5cbb84f0ed13209b20913cbf0eafa0c7928df7f135bf5"
      define_method(:install) do
        bin.install "go-argo-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v0.1.0/go-argo-mcp_Linux_arm64.tar.gz"
      sha256 "542411dd02b2f3c29ec2140d55fb9e986148aa6943fe902b3e73730f410bee6c"
      define_method(:install) do
        bin.install "go-argo-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      go-argo-mcp exposes Streamable HTTP at http://127.0.0.1:8080/rpc.
      Set ARGO_BASE_URL and optional ARGO_NAMESPACE before starting it.
    EOS
  end

  test do
    system bin/"go-argo-mcp", "--version"
  end
end
