# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lagotto < Formula
  desc "Sniff out Go layout smells (Receiver Monolith, Decomposition Theatre, Aggregate Holder, and more)."
  homepage "https://github.com/CaliLuke/lagotto"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CaliLuke/lagotto/releases/download/v0.2.0/lagotto_0.2.0_darwin_amd64.tar.gz"
      sha256 "bd04d5dc431358ca6c3b22d2cd3a44c1bf3aa527eced39c8492999e405d15111"

      define_method(:install) do
        bin.install "lagotto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CaliLuke/lagotto/releases/download/v0.2.0/lagotto_0.2.0_darwin_arm64.tar.gz"
      sha256 "e60a3fb9d8424e3c726a70e3fa27533c38dd043d68aec8a84d4384ffe6d187d2"

      define_method(:install) do
        bin.install "lagotto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/lagotto/releases/download/v0.2.0/lagotto_0.2.0_linux_amd64.tar.gz"
      sha256 "1e20e88cbc40aab83758fcb8de40f425596f8a4d92f592cb5300c1a7a1ba91dd"
      define_method(:install) do
        bin.install "lagotto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/lagotto/releases/download/v0.2.0/lagotto_0.2.0_linux_arm64.tar.gz"
      sha256 "e0043d5d7c899ab8a748d0bd8a118c2b7f7847938c3f642adc361b231931745b"
      define_method(:install) do
        bin.install "lagotto"
      end
    end
  end

  test do
    system bin/"lagotto", "--version"
  end
end
